wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682472828.933225
    t:
      1:
      - 49
      - 51
      - 55
      - 86
      2:
      - 49
      - 51
      - 55
      - 86
      3:
      - 2
      - 23
      - 24
      4: 3.9.13
      5: 0.15.0
      8:
      - 4
      - 5
